# Generated by Django 4.0.3 on 2022-04-06 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveIntegerField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('lamborghini', 'Lambo'), ('ferrari', 'Ferrari'), ('porche', 'Porche')], max_length=32)),
                ('photo', models.ImageField(blank=True, upload_to='cars')),
                ('price', models.PositiveIntegerField(blank=True)),
                ('is_sold', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=256)),
                ('car', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('writer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoughtCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('racer', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
