# Generated by Django 4.0.3 on 2022-04-06 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_photo', models.ImageField(blank=True, upload_to='profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=24)),
                ('last_name', models.CharField(blank=True, max_length=24)),
                ('money', models.FloatField(blank=True, default=0)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('is_complete', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
